name: Update Registry Index

on:
  push:
    branches: [main]
    paths:
      - 'components/**'
  pull_request:
    branches: [main]
    paths:
      - 'components/**'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC

jobs:
  update-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Generate registry index
        run: |
          node -e "
            const fs = require('fs');
            const path = require('path');
            
            const components = [];
            const componentsDir = 'components';
            
            if (fs.existsSync(componentsDir)) {
              const namespaces = fs.readdirSync(componentsDir);
              
              for (const namespace of namespaces) {
                const namespacePath = path.join(componentsDir, namespace);
                if (fs.statSync(namespacePath).isDirectory()) {
                  const componentDirs = fs.readdirSync(namespacePath);
                  
                  for (const componentName of componentDirs) {
                    const componentPath = path.join(namespacePath, componentName);
                    if (fs.statSync(componentPath).isDirectory()) {
                      const versions = fs.readdirSync(componentPath);
                      const latestVersion = versions.sort().pop();
                      
                      if (latestVersion) {
                        const registryPath = path.join(componentPath, latestVersion, 'registry.json');
                        if (fs.existsSync(registryPath)) {
                          try {
                            const metadata = JSON.parse(fs.readFileSync(registryPath, 'utf8'));
                            components.push({
                              name: \`\${namespace}/\${componentName}\`,
                              description: metadata.description || '',
                              author: metadata.author || '',
                              categories: metadata.categories || [],
                              version: latestVersion,
                              lastUpdated: new Date().toISOString()
                            });
                          } catch (error) {
                            console.error(\`Error parsing \${registryPath}:\`, error.message);
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
            
            // Sort by last updated
            components.sort((a, b) => new Date(b.lastUpdated) - new Date(a.lastUpdated));
            
            fs.writeFileSync('registry.json', JSON.stringify(components, null, 2));
            console.log(\`Updated registry index with \${components.length} components\`);
          "
          
      - name: Commit and push changes
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add registry.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update registry index [skip ci]"
            git push origin main
          fi
